version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - sealogix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data
    volumes:
      - ../models:/app/models
      - ../data:/app/data
    networks:
      - sealogix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scheduler:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    command: python -m data_pipeline.scheduler
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data
    volumes:
      - ../models:/app/models
      - ../data:/app/data
    networks:
      - sealogix-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  sealogix-network:
    driver: bridge

volumes:
  models:
    driver: local
  data:
    driver: local
